Godeps/Godeps.json
Godeps/Readme
match/mock_match.go
route/request_router.go

I've added [Godep](https://github.com/tools/godep) support, so that we can easily find the versions of the packages that work with our code as there might be breaking changes in the next versions of our dependencies.
In addition to that, I've changed a little bit the logging not to write to log when the path is not matched, so that the log won't grow too much when you have many configurations.

added godeps + not logging when the path is not matched

---

definition/file_definition.go

This commit updates the `WatchDir` method to use `Watcher`'s new API, replacing `Add` with `AddRecursive` since the `Add` method is no longer recursive by default.

Use Watcher's AddRecursive method

---

definition/mapping.go

On start, _mmock_ is listening to changes in the config, but it isn't bind, therefore the config is not updated. Only the first call to the config API triggers the binding

Bind the config to react to config changes on start

---

vars/processor_test.go
vars/request.go

This PR implements the possibility of access to an array index in dynamic responses.
Til now you could have access to entire objects and currently you can access to specific key inside an array in case you have.
So like could be seen in the updated test, you could specify a dynamic response with a key like this:
`{{request.body.friends.0}}`
Even if the it's a composite array, you could access to a property of it in this way:
`{{request.body.friends.0.some_property_which_you_wanna_get}}`
- In the case that you would have a property called `0`which it's not an index part of array the behavior continues being the same.
- In the supposed case that specifies a undefined index the behavior is the same that accessing to non-declarated property.

FEATURE: Implements access to array indexes in dynamic response

---

README.md
console/dispatcher.go
match/spy_test.go
scenario/director.go
scenario/memory_store.go
scenario/memory_store_test.go

When building mocks for developing a web ui against setting and pausing state to stay in the middle of a scenario would be super handy... so here it is.
Hope this meets all standards, happy to make any improvements first.

Add scenario set and pause state endpoints

---

Dockerfile
definition/config_mapper_test.go
definition/parser/yaml_reader_test.go
server/dispatcher.go

Creates runtime image without full go tooling in it; only 15 megs instead of 280 megs.
Also cleans up go vet errors around Error/Errorf and Print/Printf so it will build on go1.10

Use builder/runtime pattern in Dockerfile

---

Dockerfile
server/dispatcher.go

Solution: allow a 'ca.crt' to be part of the tls directory and loaded
as the certpool for the tls config on the server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jmartin82/mmock/54)

Problem: can't use custom ca certs in mmock server

---

server/dispatcher.go

@jmartin82 I did this change in order to change the behavior of the proxy when the mock path contains '*'
For the mock I copied at the bottom of my comment, the behavior on production is that any request that matches the path `papipay/*` (/papipay/girl, /papipay/video...) will be proxied to "http://dev.members.badoink.com/papipay/". This is **not** wrong but I am not sure if it makes much sense proxying all these different requests to the same url. With my change, the same mock copied below would proxy the following request:
```http://192.168.20.133:8083/papipay/girls?paysite_name=badoinkvr```
to:
```http://dev.members.badoink.com/papipay/girls?paysite_name=badoinkvr```
What do you think? Feel free to accept this change, improve or reject it. We could implement a solution for this in our …

VRS-1013 if a mock path is /whatever/* use the value of * for the proxy

---

definition/config_mapper.go

I try to use YAML config.
It insert \n at the end of request body when I use JSON format in the request body.
This PR remove \n at the end of request body for YAML config.

[FIX] remove \n at the end of request body for YAML

---

match/tester.go
match/tester_test.go

Fix problem that state doesn't match if state include Upper case.
There are 2 mock definitions(excerpt about scenario).
I call Definition2 mock after Definition1 mock, Definition2 doesn't match for state problem.
```json
{
"control": {
"scenario": {
"name": "test",
"requiredState": [
"not_started"
],
"newState": "Test"
}
}
}
```
```json
{
"control": {
"scenario": {
"name": "test",
"requiredState": [
"Test"
]
}
}
}
```
When Mmock store state, Mmock transfer state value to lower case.
https://github.com/jmartin82/mmock/blob/19f7e4cd68438dee8c92b725db543adc96c12b7b/scenario/memory_store.go#L30-L34
But when Tester check required state, Tester use original state value.
https://github.com/jmartin82/mmock/blob/19f7e4cd68438dee8c92b725db543adc96c12b7b/match/tester.go#L123-L136

Matching state without case

---

config/user-agent.yaml
vars/request.go
vars/request_test.go

Use request headers in mock body? #50 
Get request header and use it in the response body.
**Example**
{{request.header.User-Agent}}

[ADD] get request headers to params

---

vars/fake.go
vars/filler.go
vars/processor.go
vars/request.go
vars/stream.go
vars/stream_test.go

This change allows having repeated tags in the definitions
Fixes issue #66

Use an array of holders for every tag to allow duplicates

---

console/dispatcher.go
match/memory_store.go
match/memory_store_test.go
match/spy.go
match/store.go
mmock.go

With these changes you can get all recorded requests paginated from the console. 
The change adds a new route so its backward compatible.
Adds requested feature #67

Add a method to paginate the requests

---

README.md
console/dispatcher.go
match/memory_store.go
match/memory_store_test.go
match/spy.go
match/spy_test.go
match/store.go
mmock.go
tmpl/swagger.json

Reset clean the request stored in memory that matches a particular criteria.
Like stubbing this call also uses the same DSL to filter and query requests.
Thanks for this awesome project @jmartincmp ❤️

Add reset match endpoint

---

config/env.yaml
internal/vars/request.go
internal/vars/request_test.go

We'd like to "template" our mappings in order to make them configurable via Environment variables (mainly to be used inside a Docker Container).
This PR adds the possibility to retrieve env vars inside the mappings using `{{env.ENV_NAME}}`.

Add support for environment variables

---

internal/config/parser/json_reader_test.go
internal/config/parser/yaml_reader_test.go
internal/server/dispatcher.go
pkg/mock/definition.go
pkg/mock/definition_test.go

This will show an error if the duration definition is not valid while parsing the config file instead of silencing it

Return error while parsing duration during unmarshalling

---

cmd/mmock/main.go

The start of the banner contains 2 tabs while all other rows are prefixed with spaces. This means that the banner is not displayed nicely in some terminals.
It bothered me enough to create this PR. I feel like social distancing is getting to me. 🙈

Fix banner

---

README.md
config/callback.yaml
internal/server/dispatcher.go
internal/server/handle_callback.go
internal/server/handle_callback_test.go
pkg/mock/definition.go
pkg/vars/evaluator.go
pkg/vars/evaluator_test.go

This commit adds support for a callback in config. This allows mocking an API which will asynchronously make another API request as part of its contract.
A callback consists of a delay, a URL, a HTTP method, headers and a body. After the Delay, a  request is made to the given URL with the requested method/headers/body. The same substitutions are supported in the callback body as a response body, so eg. request values/fake data can be part of the API call made.
TODO:

Add support for callback (#110)

---

pkg/vars/request.go

Parsing request body params doesn't work for custom media types that support JSON like JSON+API spec
```
application/vnd.api+json
```
This change accepts any content type in the form `application/*json`

Accepts custom JSON compatible content-types when parsing body params

---

README.md
internal/console/dispatcher.go
pkg/match/scenario_store.go

Adding a new endpoint to console to display all the active scenarios and their current state
- Simply send a GET request to `{{mmock_console_url}}/api/scenarios`. 
- Response is a json representing a list of scenarios along with their current state
- The Json only includes the active (started) scenarios, any scenarios that aren't started yet will not be included in the list
https://user-images.githubusercontent.com/57954769/121661777-d9a74f00-caa4-11eb-8052-32ac7d0601c3.mov

Adding /api/scenarios endpoint to list active scenarios

---

README.md
pkg/match/payload/json_comparator.go
pkg/match/payload/json_comparator_test.go

Resolves #150 
This feature request proposes the addition of support for using regular expressions to validate and match field values within JSON request bodies. This enhancement aims to provide more flexibility and power in handling JSON requests, especially in scenarios requiring complex validation rules or pattern matching.
In many applications, especially those involving data validation and filtering, the need to use regular expressions for field values is common. Regular expressions provide a robust and flexible method for pattern matching, which can greatly enhance the application's ability to process and validate complex data structures. Adding support for regular expressions in JSON request bodies would enable developers to define more sophisticated validation rules and data …

Support Regular Expressions for Field Values in JSON Request Body

---

pkg/route/route.go
pkg/route/route_test.go

Hi Jordi,
After upgrading from `v3.0.1` to `v3.1.6` path parameters with prefixes (i.e.: `/fruits/prefix-:fruit`) stopped working.
Here is a fix for this situation.
Thank you

Fix prefix in path parameter issue

---

internal/server/router.go
pkg/match/request.go

It looks like the intention was to supress ErrPathNotMatch messages from being logged. 
This PR makes that happen.

suppress ErrPathNotMatch messages

---

README.md

Hi,
I have raised a PR to fix a typo on the README section to display scheme, hostname and port.
Thank you.

Fixed typo request.authority in README.md

---

Dockerfile

Bump Docker base image to [Alpine Linux](https://hub.docker.com/_/alpine) 3.20 and make health check less verbose by adding `--silent --show-error` to the cURL command.
<details>
<summary>`docker scout cves` output before</summary>
```text
❯ docker scout cves jordimartin/mmock
i New version 1.12.0 available (installed version is 1.11.0) at https://github.com/docker/scout-cli
✓ SBOM of image already cached, 49 packages indexed
✗ Detected 2 vulnerable packages with a total of 11 vulnerabilities
│           Analyzed Image            
────────────────────┼─────────────────────────────────────
Target            │  jordimartin/mmock:latest           
digest          │  bd8a572b79c7                       
platform        │ linux/arm64                         
vulnerabilities │    1C     2H …
```

Bump Docker base image to Alpine Linux 3.20
